hello/urls.py
from django.urls import path
from . import views

#added app name so links don't crosslink and link unneccesary pages due to toomany index.html files
app_name = "hello"

urlpatterns=[
    path("" , views.index , name="index"),
     path("index1" , views.index1 , name="index1"),
   path("<str:name>" ,views.greet , name ="greet"),
   
    ]

lecture3/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("hello.urls")),  #'hello' -----> ''
    path('newyear/' , include("newyear.urls")),
    path('tasks/' , include("tasks.urls") ),
]

newyear/urls.py
from django.urls import path
from . import views

#added app name so links don't crosslink and link unneccesary pages due to toomany index.html files
app_name = "newyear"
urlpatterns =[
    path("" , views.index , name = "index"),
]

tasks/urls.py
from django.urls import path
from . import views

#added app name so links don't crosslink and link unneccesary pages due to toomany index.html files
app_name = 'tasks'

urlpatterns =[
    path("index/" , views.index , name ="index"),
    path("add/" , views.add , name="add"),
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render (request, "hello/index.html")


def greet(request,name):
    return render(request, "hello/greet.html" ,
                  {
                      "name" : name.capitalize()
                  })


def index1(request):
    return render( request , "hello/index1.html")

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render( request , "newyear/index.html" , {
        "newyear":True
    })

tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label = "new Task")
 
   
# Create your views here.
def index(request):
    
    # Check if there already exists a "tasks" key in our session

    if "tasks" not in request.session:

        # If not, create a new list
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

# Add a new task:
def add(request):
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewTaskForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            task = form.cleaned_data["task"]

            # Add the new task to our list of tasks
            request.session["tasks"] = [task]

            # Redirect user to list of tasks
            return HttpResponseRedirect(reverse("tasks:index"))
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/505_404.html
<!DOCTYPE html>
<html>
<head>
    <title>404 or 505 Error</title>
</head>
<body>
    <h1>Page Not Found (404) or (505)</h1>
    <p>The requested page does not exist.</p>
</body>
</html>

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>GREETING WITH NAME</title>
</head>
<body>
   <h1>
    good evening , {{name}} 
   </h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAYING HELLO</title>
</head>
<body>
    <h1>hello everyone</h1>
</body>
</html>

hello/templates/hello/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Welcome to the world
</body>
</html>

newyear/templates/newyear/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IS IT REALLY NEWYEAR TODAY</title>
</head>
<body>
    
    {% if newyear%}
    <h1>YES</h1>

    {% else%}
    <h1>NO</h1>
    {%  endif %}
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}

<h1>
    ADD TASKS :
</h1>
<form  action="{% url 'tasks:add' %}" method="post">
    <!--added csrf token because after adding it wasn't taking the value and adding to another page-->
    {% csrf_token %}
    {{form}}
    <input type="submit" value="add task to list"><a href ="{% url 'tasks:index'%}">
        <br>view  all tasks</a>
    
    <br>
</form>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>TASKS</h1>
    <ul>
        {% for task in tasks%}
        <li>
            {{tasks}}
        </li>
        {%empty%}
        <li>no tasks</li>
        {% endfor %}
    </ul>
    
        <a href ="{% url 'tasks:add'%}">add tasks</a>
     

{% endblock %}
 

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TASKS</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>